In [44]:
# baca data
import pandas as pd
url=("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
headers=["sepal_length", "sepal_width", "petal_length", "petal_width", "class_label"]
datairis = pd.read_csv(url, names=headers)
print("===============================================================================")
print("                                  Data head")
print("===============================================================================")
print(datairis.head())

#pisah fitur dengan kelas
import numpy as np
fitur=np.array(datairis[["sepal_length", "sepal_width", "petal_length", "petal_width"]])
kelas=np.array(datairis["class_label"])

# import scv dan training model
from sklearn.svm import SVC
modeliris = SVC(decision_function_shape='ovo')
modeliris.fit(fitur, kelas)

# test model
print("\n\n==================================================")
print("                    Test Model")
print("==================================================")
print("Kelas untuk data [5,3,1.6,0.3] :", modeliris.predict([[5,3,1.6,0.3]]))

# melihat nilai mana saja yang menjadi support vector
print("\n\n=====================================================")
print(" Melihat model mana saja yang menjadi support vector")
print("=====================================================")
print(modeliris.support_vectors_)

# data index baris ke berapa saja yang menjadi support vector
print("\n\n=====================================================================")
print(" Melihat data index baris ke berapa saja yang menjadi support vector")
print("=====================================================================")
print(modeliris.support_)

# melihat banyaknya data yg menjadi support vector dalam setiap kelas
print("\n\n=====================================================================")
print(" Melihat banyaknya data yg menjadi support vector dalam setiap kelas")
print("=====================================================================")
print(modeliris.n_support_)

                                  Data head
   sepal_length  sepal_width  petal_length  petal_width  class_label
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


                    Test Model
Kelas untuk data [5,3,1.6,0.3] : ['Iris-setosa']


 Melihat model mana saja yang menjadi support vector
[[5.7 3.8 1.7 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [4.5 2.3 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [5.6 3.  4.5 1.5]
 [6.2 2.2 4.5 1.5]
 [5.9 3.2 4.8 1.8]
 [6.3 2.5 4.9 1.5]
 [6.1 

<h1>Latihan</h1>

Cobalah dengan iris dengan ciri-ciri lain <br>
Lihatlah support vector pada multiclass tersebut

In [45]:
print("Kelas untuk data [6.2,4,2.2,2.7] :", modeliris.predict([[6.2,4,2.2,2.7]]))

# melihat nilai mana saja yang menjadi support vector
print("\n\n=====================================================")
print(" Melihat model mana saja yang menjadi support vector")
print("=====================================================")
print(modeliris.support_vectors_)

# data index baris ke berapa saja yang menjadi support vector
print("\n\n=====================================================================")
print(" Melihat data index baris ke berapa saja yang menjadi support vector")
print("=====================================================================")
print(modeliris.support_)

# melihat banyaknya data yg menjadi support vector dalam setiap kelas
print("\n\n=====================================================================")
print(" Melihat banyaknya data yg menjadi support vector dalam setiap kelas")
print("=====================================================================")
print(modeliris.n_support_)
print("Detail :")
print(f"Jumlah SV kelas iris-setosa     : {modeliris.n_support_[0]}")
print(f"Jumlah SV kelas iris-versicolor : {modeliris.n_support_[1]}")
print(f"Jumlah SV kelas iris-virginica  : {modeliris.n_support_[2]}")

Kelas untuk data [6.2,4,2.2,2.7] : ['Iris-versicolor']


 Melihat model mana saja yang menjadi support vector
[[5.7 3.8 1.7 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [4.5 2.3 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [5.6 3.  4.5 1.5]
 [6.2 2.2 4.5 1.5]
 [5.9 3.2 4.8 1.8]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.  2.3 3.3 1. ]
 [5.1 2.5 3.  1.1]
 [5.8 2.7 5.1 1.9]
 [4.9 2.5 4.5 1.7]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [5.7 2.5 5.  2. ]
 [6.5 3.  5.5 1.8]
 [6.  2.2 5.  1.5]
 [5.6 2.8 4.9 2. ]
 [6.3 2.7 4.9 1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.